spring:
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
          #id唯一
        - id: user-server
          uri: lb://user-server
          #断言
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: demo-server
          uri: lb://demo-server
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

