server:
  port: 8080

spring:
  application:
    name: auth-server

  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo_user?&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Hongkong

  ## nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      client:
        access-token-uri: http://localhost:8080/oauth/token
        user-authorization-uri: http://localhost:8080/oauth/authorize
        ## appId
        client-id: client_code
        ## appSecret
        client-secret: 123456
  security:
    user:
      name: admin
      password: admin


## security oauth2 认证配置
security:
  oauth2:
    resource:
      ## 从认证授权中心上验证token
      token-info-uri: http://localhost:8080/oauth/check_token
      prefer-token-info: true
    client:
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8091/oauth/authorize

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        #只打印基本信息，包括请求方法、请求地址、响应状态码、请求时长
        #feign全局日志打印级别
        #NONE（默认）  不记录任何日志
        #BASIC  仅记录请求方法，URL，响应状态代码以及执行时间（适合生产环境）
        #HEADERS  记录BASIC级别的基础上，记录请求和响应的header
        #FULL   记录请求和响应header，body和元数据
        loggerLevel: BASIC
  httpclient:
    connection-timeout: 3000
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
debug: true
