server:
  port: 8080
spring:
  application:
    name: auth-server
  ## nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


management:
  endpoint:
    health:
      enabled: true
