rocketmq:
  #对应RocketMQ的Nameserver服务 多个用;分割
  name-server: 127.0.0.1:9876
  consumer:
    #组名
    group: anran-consumer-group
    #监听主题
    topic: anran-topic
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）
    tags: anran-sync-tags||anran-async-tags||anran-oneway-tags
