spring:
  redis:
    # Redis数据库索引 （默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器链接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    lettuce:
      pool:
        #连接池最大连接数 默认8，负数标识没有限制
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
        max-wait: -1
        #连接池中的最大空闲连接 默认8
        max-idle: 8
        #连接池中的最小空间连接 默认0
        min-idle: 0

      #    # Redis服务器连接密码 （默认为空）
#    password:
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      ##        max-wait: -1
    ##        # 连接池中的最大空间连接
    ##        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0
#debug: true