server:
  port: 8095
spring:
  application:
    name: rocketMQ

rocketmq:
  #对应RocketMQ的Nameserver服务 多个用;分割
  name-server: 127.0.0.1:9876
  #生产者配置
  producer:
    #组名
    group: rocket-group
    #目的地（topic:tag)
    #topic
    topic: anran-topic
    #sync tag (同步消息tag)
    sync-tag: anran-sync-tags
    #async tag (异步消息tag)
    async-tag: anran-async-tags
    #oneway tag(单向消息tag)
    oneway-tag: anran-oneway-tags
    send-message-timeout: 3000